const people = {
    1: {
        firstName: "Bill",
        lastName: "Gates",
        dob: "1977-08-16",
        address: "1 Microsoft Close",
        postcode: "MC0 5FT",
        guardian: false,
        phone: '07123123123',
        email: false,
        ethnicity: "White British",
        gender: "male",
        language: "English",
        religion: "None",
        medical: "ADHD",
        diet: false
    },
    2: {
        firstName: "Stephen",
        lastName: "Jobbs",
        dob: "1993-11-1",
        address: "23 Orchard Way",
        postcode: "AP3 0SX",
        guardian: false,
        phone: "07912345677",
        email: false,
        ethnicity: "White British",
        gender: "female",
        language: "English",
        religion: "None",
        medical: false,
        diet: "Vegetarian"
    },
    3: {
        firstName: "Linus",
        lastName: "Torvalds",
        dob: "1991-09-01",
        address: "512 dontuse rd",
        postcode: "SW18 4NY",
        guardian: false,
        phone: "07856128823",
        email: false,
        ethnicity: "White British",
        gender: "male",
        language: "English",
        religion: "Christian",
        medical: false,
        diet: false
    }
};

const attendance = {};

const selections = {
    'ethnicities': [
        "Not Known",
        "Refuse to say",
        "Albanian",
        "Arab",
        "Bangladeshi",
        "Black African",
        "Black British",
        "Black Carribean",
        "Black Congolese",
        "Black Nigerian",
        "Black Somali",
        "Chinese",
        "Gypsy/Roma",
        "Indian",
        "Iranian",
        "Iraqi",
        "Kosovan",
        "Kurdish",
        "Latin/South/Central American",
        "Moroccan",
        "Other",
        "Other Asian background",
        "Other black background",
        "Other mixed background",
        "Other white background",
        "Pakistani",
        "Traveller",
        "White and Asian",
        "White and black African",
        "White and black Carribean",
        "White British",
        "White European",
        "White Irish",
    ],
    'genders': [
        'Male',
        'Female',
        'Gender Neutral/Non-binary/Other',
        'Not specified',
        'Unknown',
        'Refuse to Say'
    ],
    'languages': [
        "Acholi",
        "Afar-Saho",
        "Afrikaans",
        "Akan (Fante)",
        "Akan (Twi / Asante)",
        "Akan / Twi-Fante",
        "Albanian / Shqip",
        "Alur",
        "Amharic",
        "Arabic",
        "Arabic (Algeria)",
        "Arabic (Any Other)",
        "Arabic (Iraq)",
        "Arabic (Morocco)",
        "Arabic (Sudan)",
        "Arabic (Yemen)",
        "Armenian",
        "Azeri",
        "Balochi",
        "Bemba",
        "Bengali",
        "Bengali (Any Other)",
        "Bengali (Sylheti)",
        "Bosnian",
        "British Sign Language",
        "Bulgarian",
        "Burmese / Myanma",
        "Caribbean Creole English",
        "Caribbean Creole French",
        "Catalan",
        "Chechen",
        "Chinese",
        "Chinese (Any Other)",
        "Chinese (Cantonese)",
        "Chinese (Hakka)",
        "Chinese (Mandarin / Putonghua)",
        "Classification Pending",
        "Cornish",
        "Croatian",
        "Czech",
        "Danish",
        "Dari Persian",
        "Dinka / Jieng",
        "Dutch / Flemish",
        "Ebira",
        "Edo / Bini",
        "Efik-Ibibio",
        "English",
        "Esan / Ishan",
        "Estonian",
        "Ewe",
        "Farsi / Persian (Any Other)",
        "Filipino",
        "Finnish",
        "French",
        "Ga",
        "Gaelic (Scotland)",
        "Gaelic / Irish",
        "Georgian",
        "German",
        "Greek",
        "Greek (Cyprus)",
        "Guarani",
        "Gujarati",
        "Hausa",
        "Hebrew",
        "Hindi",
        "Hungarian",
        "Iban",
        "Igbo",
        "Ijo (Any)",
        "Ilokano",
        "Indonesian / Bahasa Indonesia",
        "Italian",
        "Italian (Any Other)",
        "Italian (Sicilian)",
        "Japanese",
        "Katchi",
        "Kinyarwanda",
        "Kisii / Ekegusii (Kenya)",
        "Konkani",
        "Korean",
        "Krio",
        "Kurdish",
        "Kurdish (Any Other)",
        "Lango (Uganda)",
        "Latvian",
        "Lingala",
        "Lithuanian",
        "Luganda",
        "Lugbara",
        "Luo (Kenya / Tanzania)",
        "Macedonian",
        "Malay (Any Other)",
        "Malay / Indonesian",
        "Malayalam",
        "Maltese",
        "Manding / Malinke",
        "Manx Gealic",
        "Maori",
        "Marathi",
        "Mauritian / Seychelles Creole",
        "Maya (Any)",
        "Mende",
        "Mongolian (Khalkha)",
        "Nepali",
        "Norwegian",
        "Ogoni (Any)",
        "Oromo",
        "Pahari (Pakistan)",
        "Panjabi",
        "Panjabi (Any Other)",
        "Pashto / Pakhto",
        "Persian / Farsi",
        "Polish",
        "Portugese",
        "Portugese (Any Other)",
        "Portugese (Brazil)",
        "Rajathani / Marwari",
        "Romani (International)",
        "Romanian",
        "Romanian (Romania)",
        "Romany / English Romanes",
        "Runyoro-Rutooro",
        "Russian",
        "Serbian",
        "Serbian / Croatian / Bosnian",
        "Shona",
        "Sign Language (Other)",
        "Sindhi",
        "Sinhala",
        "Slovak",
        "Somali",
        "Spanish",
        "Swahili (Any Other)",
        "Swahili (Brava / Mwiini)",
        "Swahili / Kiswahili",
        "Swedish",
        "Tagalog",
        "Tagalog / Filipino",
        "Tamil",
        "Temne",
        "Thai",
        "Tigre",
        "Tigrinya",
        "Turkish",
        "Ukranian",
        "Urdu",
        "Urhobo-Isoko",
        "Uzbek",
        "Venda",
        "Vietnamese",
        "Welsh / Cymraeg",
        "Yao / Chiyao (East Africa)",
        "Yiddish",
        "Yoruba"
    ],
    'religions': [
        "Buddhist",
        "Christian",
        "Hindu",
        "Jewish",
        "Muslim",
        "Sikh",
        "No religion",
        "Other religions",
        "Religion not stated"
    ],

    'schools': [
        "Other / Not a Richmond/Wandsworth School",
        "Al Risalah School",
        "Albemarle Primary School",
        "Alderbrook Primary School",
        "All Saints CE Primary School",
        "Allfarthing Primary School",
        "Archdeacon Cambridge's CE Primary School",
        "Ark Putney Academy",
        "Ashcroft Technology Academy",
        "Athelstan House School, Hampton",
        "Azbuka Russian-English School, Mortlake",
        "Balham Nursery",
        "Barnes Primary School",
        "Beatrix Potter Primary School",
        "Belleville Primary School",
        "Bertrum House School",
        "Bishop Perrin CE Primary School",
        "Bolingbroke Academy",
        "Bradstow School",
        "Brandlehow Primary School",
        "Broadwater Primary School",
        "Broomfield House School, Kew",
        "Broomwood Hall School",
        "Buckingham Primary School",
        "Burntwood School",
        "Carlisle Infant School",
        "Centre Academy London",
        "Chase Bridge Primary School",
        "Chesterton Primary School",
        "Chestnut Grove Academy",
        "Christ's School",
        "Christchurch CE Primary School",
        "Clarendon School",
        "Collis Primary School",
        "Darell Primary School",
        "Deer Park School",
        "Dolphin School",
        "Eardley Primary School",
        "Earlsfield Primary School",
        "East Sheen Primary School",
        "Eastwood Nursery School",
        "Eaton House The Manor School",
        "Emanuel School",
        "Ernest Bevin College",
        "Eveline Day School",
        "Falconbrook Primary School",
        "Falcons Preparatory School for boys",
        "Finton House School",
        "Fircroft Primary School",
        "Floreat Wandsworth Primary School",
        "Franciscan Primary School",
        "Furzedown Primary School",
        "Garratt Park School",
        "Gatton Primary School",
        "German School London, Petersham",
        "Granard Primary School",
        "Graveney School",
        "Greenmead School",
        "Grey Court School",
        "Griffin Primary School",
        "Hall School Wimbledon",
        "Hampton Court House, East Molesey",
        "Hampton High",
        "Hampton Hill Junior School",
        "Hampton Infant School",
        "Hampton Junior School",
        "Hampton School, Hampton",
        "Hampton Wick Infant School",
        "Harris Academy Battersea",
        "Heathfield Infant School",
        "Heathfield Junior School",
        "Heathmere Primary School",
        "High View Primary School",
        "Hillbrook Primary School",
        "Holy Ghost RC Primary School",
        "Holy Trinity CE Primary School",
        "Honeywell Infants School",
        "Honeywell Junior School",
        "Hornsby House School",
        "Hotham Primary School",
        "Hurlingham School",
        "Ibstock Place School",
        "Jack and Jill School, Hampton",
        "John Burns Primary School",
        "Kew College, Kew",
        "Kew Green Preparatory School, Kew",
        "Kew Riverside Primary School",
        "King's House School, Richmond",
        "L'Ecole de Battersea",
        "Lady Eleanor Holles School, Hampton",
        "Linden Lodge School",
        "Lion House School",
        "Lowther Primary School",
        "Marshgate Primary School",
        "Meadlands Primary School",
        "Merlin School",
        "Mosaic Jewish Primary School",
        "Nelson Primary School",
        "Newland House School, Twickenham",
        "Newton Preparatory School",
        "Nightingale School",
        "Northcote Lodge School",
        "Oak Lodge School",
        "Oasis Academy Putney",
        "Oliver House Preparatory School",
        "Orleans Park School",
        "Orleans Primary School",
        "Our Lady of Victories RC Primary School",
        "Our Lady Queen of Heaven RC Primary School",
        "Paddock School",
        "Parkgate House School",
        "Penwortham Primary School",
        "Prospect House School",
        "Putney High School",
        "Radnor House School, Twickenham",
        "Rainbow School",
        "Ravenstone Primary School",
        "Richmond and Hillcroft Adult Community College",
        "Richmond Park Academy",
        "Richmond upon Thames College",
        "Richmond upon Thames School",
        "Riversdale Primary School",
        "Roehampton CE Primary School",
        "Ronald Ross Primary School",
        "Royal Ballet School, Richmond Park",
        "Rutherford House Primary School",
        "Sacred Heart (Battersea) RC Primary School",
        "Sacred Heart (Roehampton) RC Primary School",
        "Sacred Heart RC Primary School",
        "Saint Cecilia's Church of England School",
        "Sellincourt Primary School",
        "Shaftesbury Park Primary School",
        "Sheen Mount Primary School",
        "Sheringdale Primary School",
        "Smallwood Primary School",
        "Somerset Nursery School",
        "South Thames College",
        "Southfields Academy",
        "Southmead Primary School",
        "St Anne's CE Primary School",
        "St Anselm's RC Primary School",
        "St Boniface RC Primary School",
        "St Catherine's School, Twickenham",
        "St Edmund's RC Primary School",
        "St Elizabeth's RC Primary School",
        "St Faith's CE Primary School",
        "St Francis Xavier Sixth Form College",
        "St George's CE Primary School",
        "St James's RC Primary School",
        "St John Bosco College",
        "St John the Baptist CE Junior School",
        "St Joseph's RC Primary School",
        "St Mary Magdalen's RC Primary School",
        "St Mary's & St Peter's CE Primary School",
        "St Mary's CE Primary School",
        "St Mary's CE Primary School",
        "St Mary's Hampton CE Primary School",
        "St Mary's RC Primary School",
        "St Michael's CE Primary School",
        "St Osmund's RC Primary School",
        "St Paul's Juniors, Barnes",
        "St Paul's School, Barnes",
        "St Richard Reynolds Catholic College",
        "St Richard Reynolds RC College",
        "St Richard's CE Primary School",
        "St Stephen's CE Primary School",
        "Stanley Primary School",
        "Strathmore School",
        "Swaffield Primary School",
        "Teddington School",
        "Thames Christian College",
        "The Alton Primary School",
        "The Chelsea Group of Children",
        "The Dominie School",
        "The Falcons School for Girls",
        "The Harrodian School, Barnes",
        "The Mall School, Twickenham",
        "The Old Vicarage School, Richmond Hill",
        "The Priory Lodge School",
        "The Queen's CE Primary School",
        "The Roche School",
        "The Russell Primary School",
        "The Swedish School in London, Barnes",
        "The Vineyard School",
        "Thomas's London Day School",
        "Thomson House School",
        "Tooting Primary School",
        "Tower House School, East Sheen",
        "Trafalgar Infant School",
        "Trafalgar Junior School",
        "Trinity St Mary's CE Primary School",
        "Turing House School",
        "Twickenham Preparatory School, Twickenham",
        "Twickenham Primary Academy",
        "Twickenham School",
        "Unicorn School, Kew",
        "Waldegrave School",
        "Wandsworth Preparatory School",
        "West Hill Primary School (Wandsworth)",
        "Westbridge Primary School"
    ]
};

const data = {
    people: people,
    attendance: attendance,
    selections: selections
};

module.exports = data;